name: Search Orgs

on:
    schedule:
        - cron: "0 0 * * *" # This cron expression schedules the job to run every day at midnight UTC
    workflow_dispatch: # This allows you to manually trigger the workflow if needed

jobs:
    run-script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.14.0"

            - name: Install dependencies
              run: npm install

            - name: Create .env file
              run: |
                  echo GOOGLE_SEARCH_API_KEY=${{secrets.GOOGLE_SEARCH_API_KEY}} >> .env
                  echo MONGO_USER=${{secrets.MONGO_USER}} >> .env
                  echo MONGO_USER=${{secrets.MONGO_PASSWORD}} >> .env
                  echo SEARCH_ENGINE_ID=${{secrets.SEARCH_ENGINE_ID}} >> .env

            - name: Print .env file
              run: cat .env
            - name: Run script
              run: npm run search-orgs
